version: '3.8'

services:
  downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leo-downloader
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local   
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ZM_API_BASE_URL=https://api.zm.io.vn/v1/social/autolink
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3    